# Makefile
# (C) 2011 Akafugu Corporation
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.

MCU ?= attiny4313
F_CPU ?= 8000000L

TARGET = main

SRCS = main.c \
        display.c \
        usiTwiSlave.c

# Default values
COMMON_CATHODE ?= NO
FEATURE_SET_TIME ?= NO
FEATURE_ALPHABET ?= YES
FEATURE_CHANGE_TWI_ADDRESS ?= YES
FEATURE_SHOW_ADDRESS_ON_STARTUP ?= YES

ifeq ($(MCU), attiny4313)
  FEATURE_SET_TIME ?= YES
endif

# These will automatically be checked and set 
VALUE_DEFS += DEFAULT_BRIGHTNESS

# These will automatically be checked if they are set to YES
YESNO_DEFS += DEMO \
        COMMON_CATHODE \
        FEATURE_SET_TIME \
        FEATURE_ALPHABET \
        FEATURE_CHANGE_TWI_ADDRESS \
        FEATURE_SHOW_ADDRESS_ON_STARTUP
